version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip3 install -r requirements-LF1-HW2.txt -t package-LF1-HW2
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd package-LF1-HW2
      - zip -r9 ../deployment-package-LF1-HW2.zip .
      - cd ..
      - zip -g deployment-package-LF1-HW2.zip LF1-HW2.py

artifacts:
  files:
    deployment-package-LF1-HW2.zip